Fix failing tests windows, temp file permission
test_custom_column would raise exception
PermissionError: [WinError 32] The process cannot access the file
because it is being used by another process:
Add tearDown call and similarly for GeneralSpeciesExpanderTests

+ on label capitalise.